sudo: false
dist: trusty
language: cpp

addons:
	apt:
		sources:
			- ubuntu-toolchain-r-test
		packages:
			- g++-7
env:
	- MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

install:
- echo ${CXX}
- ${CXX} --version

before_script:
- cmake --version

script: ./build.sh
