dist: trusty
sudo: required
language: cpp

compiler:
- clang
os:
- linux

before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update
- sudo apt-get install -y libc++-dev libc++abi-dev bsdtar libedit-dev

install:
- echo ${CXX}
- ${CXX} --version

before_script:
- cmake --version

script: ./build.sh
